# Generated by Django 4.0.3 on 2022-03-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='tag',
            field=models.CharField(choices=[('Important', 'More Important'), ('General', 'Others'), ('Technical', 'Academic')], default='Others', max_length=20),
        ),
    ]
